FROM ubuntu:latest
ARG USERNAME=devuser
ARG PASSWORD=password
RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y openssh-client openssh-server
RUN systemctl enable ssh
RUN useradd -m $USERNAME && echo "$USERNAME:$PASSWORD" | chpasswd
EXPOSE 22
ENTRYPOINT service ssh restart && bash
